name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: dragon-build
        uses: DragonBuild/build@0.0.7
      
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: packages/me.kritanta.Gravitatiob.iphoneos-arm.deb
